[package]
name = "fun_2048"
version = "0.1.0"
edition = "2021"
rust-flags = ["-C", "target-cpu=x86-64-v3"]
[dependencies]
cstr = "0.2.12"
csv = "1.3.0"
lazy_static = "1.5.0"
num_enum = "0.7.2"
qmetaobject = "0.2.10"
rand = "0.8.5"
serde = { version = "1.0.203", features = ["derive"] }
